name: Elixir Workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir/OTP v1.12
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.12.2

      - name: Setup dependency tree
        run: mix deps.get

      - name: Run tests
        run: mix test
